### PR TITLE
Add scrollbars to CNA Browser

### PR DESCRIPTION
**Pull request by connorgr**
Adds scrollbars like the transcript plot to the CNA browser

### CODE REVIEW

**Comment by mdml** [comment]
Looks promising, but seems like there are some major bugs. See screencast [here](http://cl.ly/0N0I2q1N0J0k). When zooming after scrolling, the segments move to new locations and obscure the genome in the center of the view. Also, the "gene line" that marks the target gene (in this case *PDGFRA*) in red is off the bottom of the SVG for some reason.

**Comment by connorgr** [comment]
The latest commit fixes the scrolling issue. I wasn't able to replicate the gene line issue. It looks like it has the desired rendering behavior on my version.

**Comment by connorgr** [comment]
Both target gene bar height and scrolling issues are resolved by 2af6c8f and 7c425ee

**Comment by connorgr** [comment]
If you scroll and then zoom, bug still persists. Fix upcoming

**Comment by connorgr** [comment]
Scroll + zoom bug now fixed.

**Comment by mdml** [comment]
Looks great! The only issue I see is that some segments are outside the clipping rectangle. See [here](http://cl.ly/image/2E2N2f10232a).

**Comment by mdml** [comment]
I fixed the current issue by setting the `style.margin.top = 0`. However, I'm not sure how the current method for determining the height works, so we may need to come back and fix that later. I'll add an issue.

**Pull request merged**
